// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.3
// source: gender.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Gender struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt   string `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt   string `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Gender) Reset() {
	*x = Gender{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gender_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gender) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gender) ProtoMessage() {}

func (x *Gender) ProtoReflect() protoreflect.Message {
	mi := &file_gender_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gender.ProtoReflect.Descriptor instead.
func (*Gender) Descriptor() ([]byte, []int) {
	return file_gender_proto_rawDescGZIP(), []int{0}
}

func (x *Gender) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Gender) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Gender) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Gender) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Gender) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type AddGenderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *AddGenderRequest) Reset() {
	*x = AddGenderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gender_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGenderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGenderRequest) ProtoMessage() {}

func (x *AddGenderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gender_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGenderRequest.ProtoReflect.Descriptor instead.
func (*AddGenderRequest) Descriptor() ([]byte, []int) {
	return file_gender_proto_rawDescGZIP(), []int{1}
}

func (x *AddGenderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddGenderRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type AddGenderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gender *Gender `protobuf:"bytes,1,opt,name=Gender,proto3" json:"Gender,omitempty"`
}

func (x *AddGenderResponse) Reset() {
	*x = AddGenderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gender_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGenderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGenderResponse) ProtoMessage() {}

func (x *AddGenderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gender_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGenderResponse.ProtoReflect.Descriptor instead.
func (*AddGenderResponse) Descriptor() ([]byte, []int) {
	return file_gender_proto_rawDescGZIP(), []int{2}
}

func (x *AddGenderResponse) GetGender() *Gender {
	if x != nil {
		return x.Gender
	}
	return nil
}

type GetGenderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetGenderRequest) Reset() {
	*x = GetGenderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gender_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGenderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenderRequest) ProtoMessage() {}

func (x *GetGenderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gender_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGenderRequest.ProtoReflect.Descriptor instead.
func (*GetGenderRequest) Descriptor() ([]byte, []int) {
	return file_gender_proto_rawDescGZIP(), []int{3}
}

type GetGenderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Genders []*Gender `protobuf:"bytes,1,rep,name=Genders,proto3" json:"Genders,omitempty"`
}

func (x *GetGenderResponse) Reset() {
	*x = GetGenderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gender_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGenderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenderResponse) ProtoMessage() {}

func (x *GetGenderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gender_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGenderResponse.ProtoReflect.Descriptor instead.
func (*GetGenderResponse) Descriptor() ([]byte, []int) {
	return file_gender_proto_rawDescGZIP(), []int{4}
}

func (x *GetGenderResponse) GetGenders() []*Gender {
	if x != nil {
		return x.Genders
	}
	return nil
}

type GetGenderByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetGenderByIDRequest) Reset() {
	*x = GetGenderByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gender_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGenderByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenderByIDRequest) ProtoMessage() {}

func (x *GetGenderByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gender_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGenderByIDRequest.ProtoReflect.Descriptor instead.
func (*GetGenderByIDRequest) Descriptor() ([]byte, []int) {
	return file_gender_proto_rawDescGZIP(), []int{5}
}

func (x *GetGenderByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetGenderByIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gender *Gender `protobuf:"bytes,1,opt,name=Gender,proto3" json:"Gender,omitempty"`
}

func (x *GetGenderByIDResponse) Reset() {
	*x = GetGenderByIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gender_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGenderByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGenderByIDResponse) ProtoMessage() {}

func (x *GetGenderByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gender_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGenderByIDResponse.ProtoReflect.Descriptor instead.
func (*GetGenderByIDResponse) Descriptor() ([]byte, []int) {
	return file_gender_proto_rawDescGZIP(), []int{6}
}

func (x *GetGenderByIDResponse) GetGender() *Gender {
	if x != nil {
		return x.Gender
	}
	return nil
}

var File_gender_proto protoreflect.FileDescriptor

var file_gender_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8c, 0x01, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x22, 0x48, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x47, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3a,
	0x0a, 0x11, 0x41, 0x64, 0x64, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x52, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x22, 0x12, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3c,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x07, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x52, 0x07, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x22, 0x26, 0x0a, 0x14,
	0x47, 0x65, 0x74, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x3e, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x47, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a,
	0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x06, 0x47, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x32, 0xe2, 0x01, 0x0a, 0x0d, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x47, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x47,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x47,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47,
	0x65, 0x74, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x0d, 0x47,
	0x65, 0x74, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44, 0x12, 0x1b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x42, 0x79,
	0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_gender_proto_rawDescOnce sync.Once
	file_gender_proto_rawDescData = file_gender_proto_rawDesc
)

func file_gender_proto_rawDescGZIP() []byte {
	file_gender_proto_rawDescOnce.Do(func() {
		file_gender_proto_rawDescData = protoimpl.X.CompressGZIP(file_gender_proto_rawDescData)
	})
	return file_gender_proto_rawDescData
}

var file_gender_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_gender_proto_goTypes = []interface{}{
	(*Gender)(nil),                // 0: proto.Gender
	(*AddGenderRequest)(nil),      // 1: proto.AddGenderRequest
	(*AddGenderResponse)(nil),     // 2: proto.AddGenderResponse
	(*GetGenderRequest)(nil),      // 3: proto.GetGenderRequest
	(*GetGenderResponse)(nil),     // 4: proto.GetGenderResponse
	(*GetGenderByIDRequest)(nil),  // 5: proto.GetGenderByIDRequest
	(*GetGenderByIDResponse)(nil), // 6: proto.GetGenderByIDResponse
}
var file_gender_proto_depIdxs = []int32{
	0, // 0: proto.AddGenderResponse.Gender:type_name -> proto.Gender
	0, // 1: proto.GetGenderResponse.Genders:type_name -> proto.Gender
	0, // 2: proto.GetGenderByIDResponse.Gender:type_name -> proto.Gender
	1, // 3: proto.GenderService.AddGender:input_type -> proto.AddGenderRequest
	3, // 4: proto.GenderService.GetGenders:input_type -> proto.GetGenderRequest
	5, // 5: proto.GenderService.GetGenderByID:input_type -> proto.GetGenderByIDRequest
	2, // 6: proto.GenderService.AddGender:output_type -> proto.AddGenderResponse
	4, // 7: proto.GenderService.GetGenders:output_type -> proto.GetGenderResponse
	6, // 8: proto.GenderService.GetGenderByID:output_type -> proto.GetGenderByIDResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_gender_proto_init() }
func file_gender_proto_init() {
	if File_gender_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gender_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gender); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gender_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGenderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gender_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGenderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gender_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGenderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gender_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGenderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gender_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGenderByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gender_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGenderByIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gender_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gender_proto_goTypes,
		DependencyIndexes: file_gender_proto_depIdxs,
		MessageInfos:      file_gender_proto_msgTypes,
	}.Build()
	File_gender_proto = out.File
	file_gender_proto_rawDesc = nil
	file_gender_proto_goTypes = nil
	file_gender_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GenderServiceClient is the client API for GenderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GenderServiceClient interface {
	AddGender(ctx context.Context, in *AddGenderRequest, opts ...grpc.CallOption) (*AddGenderResponse, error)
	GetGenders(ctx context.Context, in *GetGenderRequest, opts ...grpc.CallOption) (*GetGenderResponse, error)
	GetGenderByID(ctx context.Context, in *GetGenderByIDRequest, opts ...grpc.CallOption) (*GetGenderByIDResponse, error)
}

type genderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGenderServiceClient(cc grpc.ClientConnInterface) GenderServiceClient {
	return &genderServiceClient{cc}
}

func (c *genderServiceClient) AddGender(ctx context.Context, in *AddGenderRequest, opts ...grpc.CallOption) (*AddGenderResponse, error) {
	out := new(AddGenderResponse)
	err := c.cc.Invoke(ctx, "/proto.GenderService/AddGender", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *genderServiceClient) GetGenders(ctx context.Context, in *GetGenderRequest, opts ...grpc.CallOption) (*GetGenderResponse, error) {
	out := new(GetGenderResponse)
	err := c.cc.Invoke(ctx, "/proto.GenderService/GetGenders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *genderServiceClient) GetGenderByID(ctx context.Context, in *GetGenderByIDRequest, opts ...grpc.CallOption) (*GetGenderByIDResponse, error) {
	out := new(GetGenderByIDResponse)
	err := c.cc.Invoke(ctx, "/proto.GenderService/GetGenderByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GenderServiceServer is the server API for GenderService service.
type GenderServiceServer interface {
	AddGender(context.Context, *AddGenderRequest) (*AddGenderResponse, error)
	GetGenders(context.Context, *GetGenderRequest) (*GetGenderResponse, error)
	GetGenderByID(context.Context, *GetGenderByIDRequest) (*GetGenderByIDResponse, error)
}

// UnimplementedGenderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGenderServiceServer struct {
}

func (*UnimplementedGenderServiceServer) AddGender(context.Context, *AddGenderRequest) (*AddGenderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddGender not implemented")
}
func (*UnimplementedGenderServiceServer) GetGenders(context.Context, *GetGenderRequest) (*GetGenderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGenders not implemented")
}
func (*UnimplementedGenderServiceServer) GetGenderByID(context.Context, *GetGenderByIDRequest) (*GetGenderByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGenderByID not implemented")
}

func RegisterGenderServiceServer(s *grpc.Server, srv GenderServiceServer) {
	s.RegisterService(&_GenderService_serviceDesc, srv)
}

func _GenderService_AddGender_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddGenderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenderServiceServer).AddGender(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GenderService/AddGender",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenderServiceServer).AddGender(ctx, req.(*AddGenderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GenderService_GetGenders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGenderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenderServiceServer).GetGenders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GenderService/GetGenders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenderServiceServer).GetGenders(ctx, req.(*GetGenderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GenderService_GetGenderByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGenderByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenderServiceServer).GetGenderByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GenderService/GetGenderByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenderServiceServer).GetGenderByID(ctx, req.(*GetGenderByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GenderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GenderService",
	HandlerType: (*GenderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddGender",
			Handler:    _GenderService_AddGender_Handler,
		},
		{
			MethodName: "GetGenders",
			Handler:    _GenderService_GetGenders_Handler,
		},
		{
			MethodName: "GetGenderByID",
			Handler:    _GenderService_GetGenderByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gender.proto",
}
